<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.27">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Tool loop – cosette</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-ed96de9b727972fe78a7b5d16c58bf87.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-3079788b0fb9d9587af933d59c4f2ea1.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="styles.css">
<meta property="og:title" content="Tool loop – cosette">
<meta property="og:description" content="A helper for using the OpenAI API">
<meta property="og:site_name" content="cosette">
<meta name="twitter:title" content="Tool loop – cosette">
<meta name="twitter:description" content="A helper for using the OpenAI API">
<meta name="twitter:card" content="summary">
</head>

<body class="nav-sidebar floating nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">cosette</span>
    </a>
  </div>
        <div class="quarto-navbar-tools tools-end">
</div>
          <div id="quarto-search" class="" title="Search"></div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./toolloop.html">Tool loop</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">cosette</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./core.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Cosette’s source</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./toolloop.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Tool loop</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#sample-data" id="toc-sample-data" class="nav-link active" data-scroll-target="#sample-data">Sample Data</a></li>
  <li><a href="#toolloop-implementation" id="toc-toolloop-implementation" class="nav-link" data-scroll-target="#toolloop-implementation"><code>toolloop</code> implementation</a>
  <ul class="collapse">
  <li><a href="#chat.toolloop" id="toc-chat.toolloop" class="nav-link" data-scroll-target="#chat.toolloop">Chat.toolloop</a></li>
  <li><a href="#test-customer-dataset" id="toc-test-customer-dataset" class="nav-link" data-scroll-target="#test-customer-dataset">Test Customer Dataset</a></li>
  <li><a href="#loop_outputs" id="toc-loop_outputs" class="nav-link" data-scroll-target="#loop_outputs">loop_outputs</a></li>
  <li><a href="#test-math-example" id="toc-test-math-example" class="nav-link" data-scroll-target="#test-math-example">Test Math Example</a></li>
  <li><a href="#error-conditions-out-of-iterations-exception-during-tool-invocation" id="toc-error-conditions-out-of-iterations-exception-during-tool-invocation" class="nav-link" data-scroll-target="#error-conditions-out-of-iterations-exception-during-tool-invocation">Error Conditions: Out of Iterations, Exception During Tool Invocation</a></li>
  </ul></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/AnswerDotAI/cosette/issues/new" class="toc-action"><i class="bi bi-github"></i>Report an issue</a></li></ul></div><div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="toolloop.html.md"><i class="bi bi-file-code"></i>CommonMark</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title">Tool loop</h1><button type="button" class="btn code-tools-button dropdown-toggle" id="quarto-code-tools-menu" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi"></i> Code</button><ul class="dropdown-menu dropdown-menu-end" aria-labelelledby="quarto-code-tools-menu"><li><a id="quarto-show-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Show All Code</a></li><li><a id="quarto-hide-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Hide All Code</a></li></ul></div></div>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<!-- WARNING: THIS FILE WAS AUTOGENERATED! DO NOT EDIT! -->
<div id="b7951c8f" class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> IPython.display <span class="im">import</span> display, Markdown, clear_output</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> pprint <span class="im">import</span> pprint</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div id="596a22f4" class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co">' '</span>.join(models)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<pre><code>'gpt-5 gpt-5-mini gpt-5-nano o1-preview o1-mini gpt-4o gpt-4o-mini gpt-4-turbo gpt-4 gpt-4-32k gpt-3.5-turbo gpt-3.5-turbo-instruct o1 o3-mini chatgpt-4o-latest o1-pro o3 o4-mini gpt-4.1 gpt-4.1-mini gpt-4.1-nano'</code></pre>
</div>
</div>
<div id="f998b27f" class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>model <span class="op">=</span> first(m <span class="cf">for</span> m <span class="kw">in</span> models <span class="cf">if</span> <span class="st">'mini'</span> <span class="kw">in</span> m)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>model</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<pre><code>'gpt-5-mini'</code></pre>
</div>
</div>
<section id="sample-data" class="level2">
<h2 class="anchored" data-anchor-id="sample-data">Sample Data</h2>
<div id="34342c4b" class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> _get_orders_customers():</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>    orders <span class="op">=</span> {</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>        <span class="st">"O1"</span>: <span class="bu">dict</span>(<span class="bu">id</span><span class="op">=</span><span class="st">"O1"</span>, product<span class="op">=</span><span class="st">"Widget A"</span>, quantity<span class="op">=</span><span class="dv">2</span>, price<span class="op">=</span><span class="fl">19.99</span>, status<span class="op">=</span><span class="st">"Shipped"</span>),</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>        <span class="st">"O2"</span>: <span class="bu">dict</span>(<span class="bu">id</span><span class="op">=</span><span class="st">"O2"</span>, product<span class="op">=</span><span class="st">"Gadget B"</span>, quantity<span class="op">=</span><span class="dv">1</span>, price<span class="op">=</span><span class="fl">49.99</span>, status<span class="op">=</span><span class="st">"Processing"</span>),</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>        <span class="st">"O3"</span>: <span class="bu">dict</span>(<span class="bu">id</span><span class="op">=</span><span class="st">"O3"</span>, product<span class="op">=</span><span class="st">"Gadget B"</span>, quantity<span class="op">=</span><span class="dv">2</span>, price<span class="op">=</span><span class="fl">49.99</span>, status<span class="op">=</span><span class="st">"Shipped"</span>)}</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>    customers <span class="op">=</span> {</span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>        <span class="st">"C1"</span>: <span class="bu">dict</span>(name<span class="op">=</span><span class="st">"John Doe"</span>, email<span class="op">=</span><span class="st">"john@example.com"</span>, phone<span class="op">=</span><span class="st">"123-456-7890"</span>,</span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>                   orders<span class="op">=</span>[orders[<span class="st">'O1'</span>], orders[<span class="st">'O2'</span>]]),</span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a>        <span class="st">"C2"</span>: <span class="bu">dict</span>(name<span class="op">=</span><span class="st">"Jane Smith"</span>, email<span class="op">=</span><span class="st">"jane@example.com"</span>, phone<span class="op">=</span><span class="st">"987-654-3210"</span>,</span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a>                   orders<span class="op">=</span>[orders[<span class="st">'O3'</span>]])</span>
<span id="cb6-12"><a href="#cb6-12" aria-hidden="true" tabindex="-1"></a>    }</span>
<span id="cb6-13"><a href="#cb6-13" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> orders, customers</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div id="207f9715" class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>orders, customers <span class="op">=</span> _get_orders_customers()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div id="2778dde0" class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> get_customer_info(</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>    customer_id:<span class="bu">str</span> <span class="co"># ID of the customer</span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>): <span class="co"># Customer's name, email, phone number, and list of orders</span></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>    <span class="co">"Retrieves a customer's information and their orders based on the customer ID"</span></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f'- Retrieving customer </span><span class="sc">{</span>customer_id<span class="sc">}</span><span class="ss">'</span>)</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> customers.get(customer_id, <span class="st">"Customer not found"</span>)</span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> get_order_details(</span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>    order_id:<span class="bu">str</span> <span class="co"># ID of the order</span></span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a>): <span class="co"># Order's ID, product name, quantity, price, and order status</span></span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a>    <span class="co">"Retrieves the details of a specific order based on the order ID"</span></span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f'- Retrieving order </span><span class="sc">{</span>order_id<span class="sc">}</span><span class="ss">'</span>)</span>
<span id="cb8-13"><a href="#cb8-13" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> orders.get(order_id, <span class="st">"Order not found"</span>)</span>
<span id="cb8-14"><a href="#cb8-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-15"><a href="#cb8-15" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> cancel_order(</span>
<span id="cb8-16"><a href="#cb8-16" aria-hidden="true" tabindex="-1"></a>    order_id:<span class="bu">str</span> <span class="co"># ID of the order to cancel</span></span>
<span id="cb8-17"><a href="#cb8-17" aria-hidden="true" tabindex="-1"></a>)<span class="op">-&gt;</span><span class="bu">bool</span>: <span class="co"># True if the cancellation is successful</span></span>
<span id="cb8-18"><a href="#cb8-18" aria-hidden="true" tabindex="-1"></a>    <span class="co">"Cancels an order based on the provided order ID"</span></span>
<span id="cb8-19"><a href="#cb8-19" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f'- Cancelling order </span><span class="sc">{</span>order_id<span class="sc">}</span><span class="ss">'</span>)</span>
<span id="cb8-20"><a href="#cb8-20" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> order_id <span class="kw">not</span> <span class="kw">in</span> orders: <span class="cf">return</span> <span class="va">False</span></span>
<span id="cb8-21"><a href="#cb8-21" aria-hidden="true" tabindex="-1"></a>    orders[order_id][<span class="st">'status'</span>] <span class="op">=</span> <span class="st">'Cancelled'</span></span>
<span id="cb8-22"><a href="#cb8-22" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> <span class="va">True</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div id="00ce0862" class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>chatkw <span class="op">=</span> <span class="bu">dict</span>(</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>    text<span class="op">=</span>{ <span class="st">"verbosity"</span>: <span class="st">"low"</span> },</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>    reasoning<span class="op">=</span>{ <span class="st">"effort"</span>: <span class="st">"minimal"</span> }</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div id="a4231dff" class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>tools <span class="op">=</span> [get_customer_info, get_order_details, cancel_order]</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>chat <span class="op">=</span> Chat(model, tools<span class="op">=</span>tools, <span class="op">**</span>chatkw)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div id="1a27c80b" class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>r <span class="op">=</span> chat(<span class="st">'Hi.'</span>)</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>r</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display cell-output-markdown">
<p>Hello! How can I help you today?</p>
<details>
<ul>
<li>id: resp_0610e51711a17c8b006943fce162a0819396584fc43c687fba</li>
<li>created_at: 1766063329.0</li>
<li>error: None</li>
<li>incomplete_details: None</li>
<li>instructions: None</li>
<li>metadata: {}</li>
<li>model: gpt-5-mini-2025-08-07</li>
<li>object: response</li>
<li>output: [ResponseReasoningItem(id=‘rs_0610e51711a17c8b006943fce1b7e08193a742dd433b62cbcb’, summary=[], type=‘reasoning’, content=None, encrypted_content=None, status=None), ResponseOutputMessage(id=‘msg_0610e51711a17c8b006943fce1dfc081939b2f726e067bd88c’, content=[ResponseOutputText(annotations=[], text=‘Hello! How can I help you today?’, type=‘output_text’, logprobs=[])], role=‘assistant’, status=‘completed’, type=‘message’)]</li>
<li>parallel_tool_calls: True</li>
<li>temperature: 1.0</li>
<li>tool_choice: auto</li>
<li>tools: [FunctionTool(name=‘get_customer_info’, parameters={‘type’: ‘object’, ‘properties’: {‘customer_id’: {‘type’: ‘string’, ‘description’: ‘ID of the customer’}}, ‘required’: [‘customer_id’], ‘additionalProperties’: False}, strict=True, type=‘function’, description=“Retrieves a customer’s information and their orders based on the customer ID”), FunctionTool(name=‘get_order_details’, parameters={‘type’: ‘object’, ‘properties’: {‘order_id’: {‘type’: ‘string’, ‘description’: ‘ID of the order’}}, ‘required’: [‘order_id’], ‘additionalProperties’: False}, strict=True, type=‘function’, description=‘Retrieves the details of a specific order based on the order ID’), FunctionTool(name=‘cancel_order’, parameters={‘type’: ‘object’, ‘properties’: {‘order_id’: {‘type’: ‘string’, ‘description’: ‘ID of the order to cancel’}}, ‘required’: [‘order_id’], ‘additionalProperties’: False}, strict=True, type=‘function’, description=‘Cancels an order based on the provided order ID:- type: boolean’)]</li>
<li>top_p: 1.0</li>
<li>background: False</li>
<li>conversation: None</li>
<li>max_output_tokens: 4096</li>
<li>max_tool_calls: None</li>
<li>previous_response_id: None</li>
<li>prompt: None</li>
<li>prompt_cache_key: None</li>
<li>prompt_cache_retention: None</li>
<li>reasoning: Reasoning(effort=‘minimal’, generate_summary=None, summary=None)</li>
<li>safety_identifier: None</li>
<li>service_tier: default</li>
<li>status: completed</li>
<li>text: ResponseTextConfig(format=ResponseFormatText(type=‘text’), verbosity=‘low’)</li>
<li>top_logprobs: 0</li>
<li>truncation: disabled</li>
<li>usage: ResponseUsage(input_tokens=136, input_tokens_details=InputTokensDetails(cached_tokens=0), output_tokens=15, output_tokens_details=OutputTokensDetails(reasoning_tokens=0), total_tokens=151)</li>
<li>user: None</li>
<li>billing: {‘payer’: ‘openai’}</li>
<li>store: True</li>
</ul>
</details>
</div>
</div>
<div id="93067a97" class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>r <span class="op">=</span> chat(<span class="st">'Can you tell me the email address for customer C2?'</span>)</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>r.output</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>- Retrieving customer C2</code></pre>
</div>
<div class="cell-output cell-output-display">
<pre><code>[ResponseReasoningItem(id='rs_0610e51711a17c8b006943fce2fb408193a0298d1762a4b19e', summary=[], type='reasoning', content=None, encrypted_content=None, status=None),
 ResponseFunctionToolCall(arguments='{"customer_id":"C2"}', call_id='call_1iQyH2m7zBT6AxtxpVfgOARS', name='get_customer_info', type='function_call', id='fc_0610e51711a17c8b006943fce34518819385d6cbeb29b1f63f', status='completed')]</code></pre>
</div>
</div>
<div id="1a6bc412" class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>r <span class="op">=</span> chat()</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>r.output</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<pre><code>[ResponseOutputMessage(id='msg_0610e51711a17c8b006943fce4a59c8193b7914069038e07b0', content=[ResponseOutputText(annotations=[], text='The email address for customer C2 is jane@example.com.', type='output_text', logprobs=[])], role='assistant', status='completed', type='message')]</code></pre>
</div>
</div>
<div id="6aa531d0" class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>chat <span class="op">=</span> Chat(model, tools<span class="op">=</span>tools)</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>r <span class="op">=</span> chat(<span class="st">'Please cancel all orders for customer C1 for me.'</span>)</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>r.output</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>- Retrieving customer C1</code></pre>
</div>
<div class="cell-output cell-output-display">
<pre><code>[ResponseReasoningItem(id='rs_067a83d17b75c4ea006943fce594008194904f7f4b1710ab11', summary=[], type='reasoning', content=None, encrypted_content=None, status=None),
 ResponseFunctionToolCall(arguments='{"customer_id":"C1"}', call_id='call_5MXLQEl4LdzFyRHIR3DynD9I', name='get_customer_info', type='function_call', id='fc_067a83d17b75c4ea006943fce6c9848194b442cb73ffe02035', status='completed')]</code></pre>
</div>
</div>
<div id="5dcdebef" class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>r <span class="op">=</span> chat()</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>r.output</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>- Cancelling order O1
- Cancelling order O2</code></pre>
</div>
<div class="cell-output cell-output-display">
<pre><code>[ResponseReasoningItem(id='rs_067a83d17b75c4ea006943fce7b6648194aa8afa477dc81c42', summary=[], type='reasoning', content=None, encrypted_content=None, status=None),
 ResponseFunctionToolCall(arguments='{"order_id":"O1"}', call_id='call_y3LWRVEn8X80nCQf50EOVOu5', name='cancel_order', type='function_call', id='fc_067a83d17b75c4ea006943fce992f88194b8de77d411f78e44', status='completed'),
 ResponseFunctionToolCall(arguments='{"order_id":"O2"}', call_id='call_oPiTCOxwXjo8uac0mzXK3rEv', name='cancel_order', type='function_call', id='fc_067a83d17b75c4ea006943fce9f498819495f077de035b7454', status='completed')]</code></pre>
</div>
</div>
</section>
<section id="toolloop-implementation" class="level2">
<h2 class="anchored" data-anchor-id="toolloop-implementation"><code>toolloop</code> implementation</h2>
<hr>
<p><a href="https://github.com/AnswerDotAI/cosette/blob/main/cosette/toolloop.py#L18" target="_blank" style="float:right; font-size:smaller">source</a></p>
<section id="chat.toolloop" class="level3">
<h3 class="anchored" data-anchor-id="chat.toolloop">Chat.toolloop</h3>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb23"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> toolloop(</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>    pr, <span class="co"># Prompt to pass to Claude</span></span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>    max_steps:<span class="bu">int</span><span class="op">=</span><span class="dv">10</span>, <span class="co"># Maximum number of tool requests to loop through</span></span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>    cont_func:<span class="bu">callable</span><span class="op">=</span>noop, <span class="co"># Function that stops loop if returns False</span></span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a>    final_prompt:<span class="bu">str</span><span class="op">=</span><span class="st">'You have no more tool uses. Please summarize your findings. If you did not complete your goal please tell the user what further work needs to be done so they can choose how best to proceed.'</span>, <span class="co"># Prompt to add if last message is a tool call</span></span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a>    stream:<span class="bu">bool</span><span class="op">=</span><span class="va">False</span>, <span class="co"># Stream response?</span></span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a>    tools:NoneType<span class="op">=</span><span class="va">None</span>, <span class="co"># Tools to use</span></span>
<span id="cb23-9"><a href="#cb23-9" aria-hidden="true" tabindex="-1"></a>    tool_choice:NoneType<span class="op">=</span><span class="va">None</span>, <span class="co"># Required tools to use</span></span>
<span id="cb23-10"><a href="#cb23-10" aria-hidden="true" tabindex="-1"></a>    background:Optional[<span class="bu">bool</span>] <span class="op">|</span> Omit<span class="op">=&lt;</span>openai.Omit <span class="bu">object</span> at <span class="bn">0x7f58df64bd40</span><span class="op">&gt;</span>,</span>
<span id="cb23-11"><a href="#cb23-11" aria-hidden="true" tabindex="-1"></a>    conversation:Optional[response_create_params.Conversation] <span class="op">|</span> Omit<span class="op">=&lt;</span>openai.Omit <span class="bu">object</span> at <span class="bn">0x7f58df64bd40</span><span class="op">&gt;</span>,</span>
<span id="cb23-12"><a href="#cb23-12" aria-hidden="true" tabindex="-1"></a>    include:Optional[List[ResponseIncludable]] <span class="op">|</span> Omit<span class="op">=&lt;</span>openai.Omit <span class="bu">object</span> at <span class="bn">0x7f58df64bd40</span><span class="op">&gt;</span>,</span>
<span id="cb23-13"><a href="#cb23-13" aria-hidden="true" tabindex="-1"></a>    <span class="bu">input</span>:Union[<span class="bu">str</span>, ResponseInputParam] <span class="op">|</span> Omit<span class="op">=&lt;</span>openai.Omit <span class="bu">object</span> at <span class="bn">0x7f58df64bd40</span><span class="op">&gt;</span>,</span>
<span id="cb23-14"><a href="#cb23-14" aria-hidden="true" tabindex="-1"></a>    instructions:Optional[<span class="bu">str</span>] <span class="op">|</span> Omit<span class="op">=&lt;</span>openai.Omit <span class="bu">object</span> at <span class="bn">0x7f58df64bd40</span><span class="op">&gt;</span>,</span>
<span id="cb23-15"><a href="#cb23-15" aria-hidden="true" tabindex="-1"></a>    max_output_tokens:Optional[<span class="bu">int</span>] <span class="op">|</span> Omit<span class="op">=&lt;</span>openai.Omit <span class="bu">object</span> at <span class="bn">0x7f58df64bd40</span><span class="op">&gt;</span>,</span>
<span id="cb23-16"><a href="#cb23-16" aria-hidden="true" tabindex="-1"></a>    max_tool_calls:Optional[<span class="bu">int</span>] <span class="op">|</span> Omit<span class="op">=&lt;</span>openai.Omit <span class="bu">object</span> at <span class="bn">0x7f58df64bd40</span><span class="op">&gt;</span>,</span>
<span id="cb23-17"><a href="#cb23-17" aria-hidden="true" tabindex="-1"></a>    metadata:Optional[Metadata] <span class="op">|</span> Omit<span class="op">=&lt;</span>openai.Omit <span class="bu">object</span> at <span class="bn">0x7f58df64bd40</span><span class="op">&gt;</span>,</span>
<span id="cb23-18"><a href="#cb23-18" aria-hidden="true" tabindex="-1"></a>    model:ResponsesModel <span class="op">|</span> Omit<span class="op">=&lt;</span>openai.Omit <span class="bu">object</span> at <span class="bn">0x7f58df64bd40</span><span class="op">&gt;</span>,</span>
<span id="cb23-19"><a href="#cb23-19" aria-hidden="true" tabindex="-1"></a>    parallel_tool_calls:Optional[<span class="bu">bool</span>] <span class="op">|</span> Omit<span class="op">=&lt;</span>openai.Omit <span class="bu">object</span> at <span class="bn">0x7f58df64bd40</span><span class="op">&gt;</span>,</span>
<span id="cb23-20"><a href="#cb23-20" aria-hidden="true" tabindex="-1"></a>    previous_response_id:Optional[<span class="bu">str</span>] <span class="op">|</span> Omit<span class="op">=&lt;</span>openai.Omit <span class="bu">object</span> at <span class="bn">0x7f58df64bd40</span><span class="op">&gt;</span>,</span>
<span id="cb23-21"><a href="#cb23-21" aria-hidden="true" tabindex="-1"></a>    prompt:Optional[ResponsePromptParam] <span class="op">|</span> Omit<span class="op">=&lt;</span>openai.Omit <span class="bu">object</span> at <span class="bn">0x7f58df64bd40</span><span class="op">&gt;</span>,</span>
<span id="cb23-22"><a href="#cb23-22" aria-hidden="true" tabindex="-1"></a>    prompt_cache_key:<span class="bu">str</span> <span class="op">|</span> Omit<span class="op">=&lt;</span>openai.Omit <span class="bu">object</span> at <span class="bn">0x7f58df64bd40</span><span class="op">&gt;</span>,</span>
<span id="cb23-23"><a href="#cb23-23" aria-hidden="true" tabindex="-1"></a>    prompt_cache_retention:Optional[Literal[<span class="st">'in-memory'</span>, <span class="st">'24h'</span>]] <span class="op">|</span> Omit<span class="op">=&lt;</span>openai.Omit <span class="bu">object</span> at <span class="bn">0x7f58df64bd40</span><span class="op">&gt;</span>,</span>
<span id="cb23-24"><a href="#cb23-24" aria-hidden="true" tabindex="-1"></a>    reasoning:Optional[Reasoning] <span class="op">|</span> Omit<span class="op">=&lt;</span>openai.Omit <span class="bu">object</span> at <span class="bn">0x7f58df64bd40</span><span class="op">&gt;</span>,</span>
<span id="cb23-25"><a href="#cb23-25" aria-hidden="true" tabindex="-1"></a>    safety_identifier:<span class="bu">str</span> <span class="op">|</span> Omit<span class="op">=&lt;</span>openai.Omit <span class="bu">object</span> at <span class="bn">0x7f58df64bd40</span><span class="op">&gt;</span>,</span>
<span id="cb23-26"><a href="#cb23-26" aria-hidden="true" tabindex="-1"></a>    service_tier:Optional[Literal[<span class="st">'auto'</span>, <span class="st">'default'</span>, <span class="st">'flex'</span>, <span class="st">'scale'</span>, <span class="st">'priority'</span>]] <span class="op">|</span> Omit<span class="op">=&lt;</span>openai.Omit <span class="bu">object</span> at <span class="bn">0x7f58df64bd40</span><span class="op">&gt;</span>,</span>
<span id="cb23-27"><a href="#cb23-27" aria-hidden="true" tabindex="-1"></a>    store:Optional[<span class="bu">bool</span>] <span class="op">|</span> Omit<span class="op">=&lt;</span>openai.Omit <span class="bu">object</span> at <span class="bn">0x7f58df64bd40</span><span class="op">&gt;</span>,</span>
<span id="cb23-28"><a href="#cb23-28" aria-hidden="true" tabindex="-1"></a>    stream_options:Optional[response_create_params.StreamOptions] <span class="op">|</span> Omit<span class="op">=&lt;</span>openai.Omit <span class="bu">object</span> at <span class="bn">0x7f58df64bd40</span><span class="op">&gt;</span>,</span>
<span id="cb23-29"><a href="#cb23-29" aria-hidden="true" tabindex="-1"></a>    temperature:Optional[<span class="bu">float</span>] <span class="op">|</span> Omit<span class="op">=&lt;</span>openai.Omit <span class="bu">object</span> at <span class="bn">0x7f58df64bd40</span><span class="op">&gt;</span>,</span>
<span id="cb23-30"><a href="#cb23-30" aria-hidden="true" tabindex="-1"></a>    text:ResponseTextConfigParam <span class="op">|</span> Omit<span class="op">=&lt;</span>openai.Omit <span class="bu">object</span> at <span class="bn">0x7f58df64bd40</span><span class="op">&gt;</span>,</span>
<span id="cb23-31"><a href="#cb23-31" aria-hidden="true" tabindex="-1"></a>    top_logprobs:Optional[<span class="bu">int</span>] <span class="op">|</span> Omit<span class="op">=&lt;</span>openai.Omit <span class="bu">object</span> at <span class="bn">0x7f58df64bd40</span><span class="op">&gt;</span>,</span>
<span id="cb23-32"><a href="#cb23-32" aria-hidden="true" tabindex="-1"></a>    top_p:Optional[<span class="bu">float</span>] <span class="op">|</span> Omit<span class="op">=&lt;</span>openai.Omit <span class="bu">object</span> at <span class="bn">0x7f58df64bd40</span><span class="op">&gt;</span>,</span>
<span id="cb23-33"><a href="#cb23-33" aria-hidden="true" tabindex="-1"></a>    truncation:Optional[Literal[<span class="st">'auto'</span>, <span class="st">'disabled'</span>]] <span class="op">|</span> Omit<span class="op">=&lt;</span>openai.Omit <span class="bu">object</span> at <span class="bn">0x7f58df64bd40</span><span class="op">&gt;</span>,</span>
<span id="cb23-34"><a href="#cb23-34" aria-hidden="true" tabindex="-1"></a>    user:<span class="bu">str</span> <span class="op">|</span> Omit<span class="op">=&lt;</span>openai.Omit <span class="bu">object</span> at <span class="bn">0x7f58df64bd40</span><span class="op">&gt;</span>,</span>
<span id="cb23-35"><a href="#cb23-35" aria-hidden="true" tabindex="-1"></a>    extra_headers:Headers <span class="op">|</span> <span class="va">None</span><span class="op">=</span><span class="va">None</span>, <span class="co"># Use the following arguments if you need to pass additional parameters to the API that aren't available via kwargs.</span></span>
<span id="cb23-36"><a href="#cb23-36" aria-hidden="true" tabindex="-1"></a>The extra values given here take precedence over values defined on the client <span class="kw">or</span> passed to this method.</span>
<span id="cb23-37"><a href="#cb23-37" aria-hidden="true" tabindex="-1"></a>    extra_query:Query <span class="op">|</span> <span class="va">None</span><span class="op">=</span><span class="va">None</span>, extra_body:Body <span class="op">|</span> <span class="va">None</span><span class="op">=</span><span class="va">None</span>,</span>
<span id="cb23-38"><a href="#cb23-38" aria-hidden="true" tabindex="-1"></a>    timeout:<span class="bu">float</span> <span class="op">|</span> httpx.Timeout <span class="op">|</span> <span class="va">None</span> <span class="op">|</span> NotGiven<span class="op">=</span>NOT_GIVEN</span>
<span id="cb23-39"><a href="#cb23-39" aria-hidden="true" tabindex="-1"></a>):</span>
<span id="cb23-40"><a href="#cb23-40" aria-hidden="true" tabindex="-1"></a></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p><em>Add prompt <code>pr</code> to dialog and get a response from Claude, automatically following up with <code>tool_use</code> messages</em></p>
<div id="e0136903" class="cell">
<details open="" class="code-fold">
<summary>Exported source</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>_final_prompt <span class="op">=</span> <span class="st">"You have no more tool uses. Please summarize your findings. If you did not complete your goal please tell the user what further work needs to be done so they can choose how best to proceed."</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<div id="84eac4c1" class="cell">
<details open="" class="code-fold">
<summary>Exported source</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="at">@patch</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a><span class="at">@delegates</span>(Chat.<span class="fu">__call__</span>)</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> toolloop(<span class="va">self</span>:Chat,</span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>             pr, <span class="co"># Prompt to pass to Claude</span></span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>             max_steps<span class="op">=</span><span class="dv">10</span>, <span class="co"># Maximum number of tool requests to loop through</span></span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a>             cont_func:<span class="bu">callable</span><span class="op">=</span>noop, <span class="co"># Function that stops loop if returns False</span></span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a>             final_prompt<span class="op">=</span>_final_prompt, <span class="co"># Prompt to add if last message is a tool call</span></span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a>             <span class="op">**</span>kwargs):</span>
<span id="cb25-9"><a href="#cb25-9" aria-hidden="true" tabindex="-1"></a>    <span class="co">"Add prompt `pr` to dialog and get a response from Claude, automatically following up with `tool_use` messages"</span></span>
<span id="cb25-10"><a href="#cb25-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">@save_iter</span></span>
<span id="cb25-11"><a href="#cb25-11" aria-hidden="true" tabindex="-1"></a>    <span class="kw">def</span> _f(o):</span>
<span id="cb25-12"><a href="#cb25-12" aria-hidden="true" tabindex="-1"></a>        init_n <span class="op">=</span> <span class="bu">len</span>(<span class="va">self</span>.h)</span>
<span id="cb25-13"><a href="#cb25-13" aria-hidden="true" tabindex="-1"></a>        r <span class="op">=</span> <span class="va">self</span>(pr, <span class="op">**</span>kwargs)</span>
<span id="cb25-14"><a href="#cb25-14" aria-hidden="true" tabindex="-1"></a>        <span class="cf">yield</span> r</span>
<span id="cb25-15"><a href="#cb25-15" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> <span class="bu">len</span>(<span class="va">self</span>.last)<span class="op">&gt;</span><span class="dv">1</span>: <span class="cf">yield</span> <span class="cf">from</span> <span class="va">self</span>.last[<span class="dv">1</span>:]</span>
<span id="cb25-16"><a href="#cb25-16" aria-hidden="true" tabindex="-1"></a>        <span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(max_steps<span class="op">-</span><span class="dv">1</span>):</span>
<span id="cb25-17"><a href="#cb25-17" aria-hidden="true" tabindex="-1"></a>            x <span class="op">=</span> <span class="va">self</span>.h[<span class="op">-</span><span class="dv">1</span>]</span>
<span id="cb25-18"><a href="#cb25-18" aria-hidden="true" tabindex="-1"></a>            <span class="cf">if</span> <span class="kw">not</span> (<span class="bu">isinstance</span>(x, <span class="bu">dict</span>) <span class="kw">and</span> x[<span class="st">'type'</span>]<span class="op">==</span><span class="st">'function_call_output'</span>): <span class="cf">break</span></span>
<span id="cb25-19"><a href="#cb25-19" aria-hidden="true" tabindex="-1"></a>            r <span class="op">=</span> <span class="va">self</span>(final_prompt <span class="cf">if</span> i<span class="op">==</span>max_steps<span class="op">-</span><span class="dv">2</span> <span class="cf">else</span> <span class="va">None</span>, <span class="op">**</span>kwargs)</span>
<span id="cb25-20"><a href="#cb25-20" aria-hidden="true" tabindex="-1"></a>            <span class="cf">yield</span> r</span>
<span id="cb25-21"><a href="#cb25-21" aria-hidden="true" tabindex="-1"></a>            <span class="cf">if</span> <span class="bu">len</span>(<span class="va">self</span>.last)<span class="op">&gt;</span><span class="dv">1</span>: <span class="cf">yield</span> <span class="cf">from</span> <span class="va">self</span>.last[<span class="dv">1</span>:]</span>
<span id="cb25-22"><a href="#cb25-22" aria-hidden="true" tabindex="-1"></a>            <span class="cf">if</span> <span class="kw">not</span> cont_func(<span class="op">*</span><span class="va">self</span>.h[<span class="op">-</span><span class="dv">3</span>:]): <span class="cf">break</span></span>
<span id="cb25-23"><a href="#cb25-23" aria-hidden="true" tabindex="-1"></a>        o.value <span class="op">=</span> <span class="va">self</span>.h[init_n<span class="op">+</span><span class="dv">1</span>:]</span>
<span id="cb25-24"><a href="#cb25-24" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> _f()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
</section>
<section id="test-customer-dataset" class="level3">
<h3 class="anchored" data-anchor-id="test-customer-dataset">Test Customer Dataset</h3>
<div id="04e3e3e0" class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb26"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> show(x):</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> <span class="bu">getattr</span>(x, <span class="st">'output_text'</span>, <span class="va">None</span>): r <span class="op">=</span> x</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>    <span class="cf">else</span>: r <span class="op">=</span> <span class="bu">getattr</span>(x,<span class="st">'output'</span>,x)</span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>    display(r)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div id="78cc0eff" class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>chat <span class="op">=</span> Chat(model, tools<span class="op">=</span>tools)</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>pr <span class="op">=</span> <span class="st">'Can you tell me the email address for customer C1?'</span></span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>r <span class="op">=</span> chat.toolloop(pr)</span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>res <span class="op">=</span> <span class="bu">list</span>(r)</span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> o <span class="kw">in</span> r: show(o)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>- Retrieving customer C1</code></pre>
</div>
<div class="cell-output cell-output-display cell-output-markdown">
<p>The email address for customer C1 (John Doe) is john@example.com.</p>
<details>
<ul>
<li>id: resp_0787bac936d9204f006943fcee2ba48195ad60e3c1ec52d1d7</li>
<li>created_at: 1766063342.0</li>
<li>error: None</li>
<li>incomplete_details: None</li>
<li>instructions: None</li>
<li>metadata: {}</li>
<li>model: gpt-5-mini-2025-08-07</li>
<li>object: response</li>
<li>output: [ResponseReasoningItem(id=‘rs_0787bac936d9204f006943fcee7cd881959b82edf88db5e70d’, summary=[], type=‘reasoning’, content=None, encrypted_content=None, status=None), ResponseOutputMessage(id=‘msg_0787bac936d9204f006943fcef3ee88195832b056ec436b34f’, content=[ResponseOutputText(annotations=[], text=‘The email address for customer C1 (John Doe) is john@example.com.’, type=‘output_text’, logprobs=[])], role=‘assistant’, status=‘completed’, type=‘message’)]</li>
<li>parallel_tool_calls: True</li>
<li>temperature: 1.0</li>
<li>tool_choice: auto</li>
<li>tools: [FunctionTool(name=‘get_customer_info’, parameters={‘type’: ‘object’, ‘properties’: {‘customer_id’: {‘type’: ‘string’, ‘description’: ‘ID of the customer’}}, ‘required’: [‘customer_id’], ‘additionalProperties’: False}, strict=True, type=‘function’, description=“Retrieves a customer’s information and their orders based on the customer ID”), FunctionTool(name=‘get_order_details’, parameters={‘type’: ‘object’, ‘properties’: {‘order_id’: {‘type’: ‘string’, ‘description’: ‘ID of the order’}}, ‘required’: [‘order_id’], ‘additionalProperties’: False}, strict=True, type=‘function’, description=‘Retrieves the details of a specific order based on the order ID’), FunctionTool(name=‘cancel_order’, parameters={‘type’: ‘object’, ‘properties’: {‘order_id’: {‘type’: ‘string’, ‘description’: ‘ID of the order to cancel’}}, ‘required’: [‘order_id’], ‘additionalProperties’: False}, strict=True, type=‘function’, description=‘Cancels an order based on the provided order ID:- type: boolean’)]</li>
<li>top_p: 1.0</li>
<li>background: False</li>
<li>conversation: None</li>
<li>max_output_tokens: 4096</li>
<li>max_tool_calls: None</li>
<li>previous_response_id: None</li>
<li>prompt: None</li>
<li>prompt_cache_key: None</li>
<li>prompt_cache_retention: None</li>
<li>reasoning: Reasoning(effort=‘medium’, generate_summary=None, summary=None)</li>
<li>safety_identifier: None</li>
<li>service_tier: default</li>
<li>status: completed</li>
<li>text: ResponseTextConfig(format=ResponseFormatText(type=‘text’), verbosity=‘medium’)</li>
<li>top_logprobs: 0</li>
<li>truncation: disabled</li>
<li>usage: ResponseUsage(input_tokens=316, input_tokens_details=InputTokensDetails(cached_tokens=0), output_tokens=86, output_tokens_details=OutputTokensDetails(reasoning_tokens=64), total_tokens=402)</li>
<li>user: None</li>
<li>billing: {‘payer’: ‘openai’}</li>
<li>store: True</li>
</ul>
</details>
</div>
<div class="cell-output cell-output-display">
<pre><code>ResponseOutputMessage(id='msg_0787bac936d9204f006943fcef3ee88195832b056ec436b34f', content=[ResponseOutputText(annotations=[], text='The email address for customer C1 (John Doe) is john@example.com.', type='output_text', logprobs=[])], role='assistant', status='completed', type='message')</code></pre>
</div>
</div>
<hr>
<p><a href="https://github.com/AnswerDotAI/cosette/blob/main/cosette/toolloop.py#L42" target="_blank" style="float:right; font-size:smaller">source</a></p>
</section>
<section id="loop_outputs" class="level3">
<h3 class="anchored" data-anchor-id="loop_outputs">loop_outputs</h3>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb30"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> loop_outputs(</span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>    res</span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>):</span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div id="fdceb37e" class="cell">
<details open="" class="code-fold">
<summary>Exported source</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb31"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> loop_outputs(res):</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> [<span class="bu">dict</span>(p) <span class="cf">for</span> o <span class="kw">in</span> res <span class="cf">for</span> p <span class="kw">in</span> ([o] <span class="cf">if</span> <span class="bu">isinstance</span>(o,<span class="bu">dict</span>) <span class="cf">else</span> <span class="bu">getattr</span>(o,<span class="st">'output'</span>,[]))]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<div id="9097035a" class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb32"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>cl <span class="op">=</span> loop_outputs(res)</span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>cl</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<pre><code>[{'id': 'rs_0787bac936d9204f006943fceb6f088195a44ade2155966909',
  'summary': [],
  'type': 'reasoning',
  'content': None,
  'encrypted_content': None,
  'status': None},
 {'arguments': '{"customer_id":"C1"}',
  'call_id': 'call_wqbYqGHnvgMg8lSY9JMUrwzU',
  'name': 'get_customer_info',
  'type': 'function_call',
  'id': 'fc_0787bac936d9204f006943fcebe6d08195b9cd3ca97a01b7d2',
  'status': 'completed'},
 {'type': 'function_call_output',
  'call_id': 'call_wqbYqGHnvgMg8lSY9JMUrwzU',
  'output': "{'name': 'John Doe', 'email': 'john@example.com', 'phone': '123-456-7890', 'orders': [{'id': 'O1', 'product': 'Widget A', 'quantity': 2, 'price': 19.99, 'status': 'Cancelled'}, {'id': 'O2', 'product': 'Gadget B', 'quantity': 1, 'price': 49.99, 'status': 'Cancelled'}]}"},
 {'id': 'rs_0787bac936d9204f006943fcec9c108195b41ad9735c482bc4',
  'summary': [],
  'type': 'reasoning',
  'content': None,
  'encrypted_content': None,
  'status': None},
 {'id': 'msg_0787bac936d9204f006943fced6e3c8195b5b4c9710ecb6485',
  'content': [ResponseOutputText(annotations=[], text='The email address for customer C1 (John Doe) is john@example.com.', type='output_text', logprobs=[])],
  'role': 'assistant',
  'status': 'completed',
  'type': 'message'}]</code></pre>
</div>
</div>
<div id="13d2b043" class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb34"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> disp_tc(x):</span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> x[<span class="st">'type'</span>]<span class="op">==</span><span class="st">'function_call'</span>: <span class="cf">return</span> <span class="ss">f"- `</span><span class="sc">{</span>x[<span class="st">'name'</span>]<span class="sc">}</span><span class="ss">(</span><span class="sc">{</span>x[<span class="st">'arguments'</span>]<span class="sc">}</span><span class="ss">)`</span><span class="ch">\n</span><span class="ss">"</span></span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>    <span class="cf">elif</span> x[<span class="st">'type'</span>]<span class="op">==</span><span class="st">'function_call_output'</span>: <span class="cf">return</span> <span class="ss">f"  - `</span><span class="sc">{</span>x[<span class="st">'output'</span>]<span class="sc">}</span><span class="ss">`</span><span class="ch">\n\n</span><span class="ss">"</span></span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a>    <span class="cf">else</span>: <span class="cf">return</span> <span class="st">''</span>.join(o.text <span class="cf">for</span> o <span class="kw">in</span> x[<span class="st">'content'</span>])</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div id="cff1f001" class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb35"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Markdown(''.join(map(disp_tc, cl)))</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div id="5c586d6a" class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb36"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>pprint(r.value)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[ResponseReasoningItem(id='rs_0787bac936d9204f006943fcee7cd881959b82edf88db5e70d', summary=[], type='reasoning', content=None, encrypted_content=None, status=None),
 ResponseOutputMessage(id='msg_0787bac936d9204f006943fcef3ee88195832b056ec436b34f', content=[ResponseOutputText(annotations=[], text='The email address for customer C1 (John Doe) is john@example.com.', type='output_text', logprobs=[])], role='assistant', status='completed', type='message')]</code></pre>
</div>
</div>
<div id="050f6591" class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb38"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>orders, customers <span class="op">=</span> _get_orders_customers()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div id="8de04256" class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb39"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>chat <span class="op">=</span> Chat(model, tools<span class="op">=</span>tools)</span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>r <span class="op">=</span> chat.toolloop(<span class="st">'What is the status of order O2?'</span>)</span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> o <span class="kw">in</span> r: display(<span class="bu">getattr</span>(o,<span class="st">'output'</span>,o))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>- Retrieving order O2</code></pre>
</div>
<div class="cell-output cell-output-display">
<pre><code>[ResponseReasoningItem(id='rs_080cc194cfa17c94006943fcf092688194adde78fdb74e90d3', summary=[], type='reasoning', content=None, encrypted_content=None, status=None),
 ResponseFunctionToolCall(arguments='{"order_id":"O2"}', call_id='call_ARnBd6xSrlcAfn3wBQGdLtiu', name='get_order_details', type='function_call', id='fc_080cc194cfa17c94006943fcf1ed8c8194adc4f0474afe98cc', status='completed')]</code></pre>
</div>
<div class="cell-output cell-output-display">
<pre><code>ResponseFunctionToolCall(arguments='{"order_id":"O2"}', call_id='call_ARnBd6xSrlcAfn3wBQGdLtiu', name='get_order_details', type='function_call', id='fc_080cc194cfa17c94006943fcf1ed8c8194adc4f0474afe98cc', status='completed')</code></pre>
</div>
<div class="cell-output cell-output-display">
<pre><code>{'type': 'function_call_output',
 'call_id': 'call_ARnBd6xSrlcAfn3wBQGdLtiu',
 'output': "{'id': 'O2', 'product': 'Gadget B', 'quantity': 1, 'price': 49.99, 'status': 'Processing'}"}</code></pre>
</div>
<div class="cell-output cell-output-display">
<pre><code>[ResponseOutputMessage(id='msg_080cc194cfa17c94006943fcf3101081948ac3faafe2dcac65', content=[ResponseOutputText(annotations=[], text='Order O2 is currently: Processing.', type='output_text', logprobs=[])], role='assistant', status='completed', type='message')]</code></pre>
</div>
</div>
<div id="f8c0fec9" class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb45"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a>r <span class="op">=</span> chat.toolloop(<span class="st">'Please cancel all orders for customer C1 for me.'</span>)</span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a>res <span class="op">=</span> <span class="bu">list</span>(r)</span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> o <span class="kw">in</span> res: display(<span class="bu">getattr</span>(o,<span class="st">'output'</span>,o))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>- Retrieving customer C1
- Cancelling order O1
- Cancelling order O2</code></pre>
</div>
<div class="cell-output cell-output-display">
<pre><code>[ResponseReasoningItem(id='rs_080cc194cfa17c94006943fcf412208194a4c7b87ce81c4736', summary=[], type='reasoning', content=None, encrypted_content=None, status=None),
 ResponseFunctionToolCall(arguments='{"customer_id":"C1"}', call_id='call_Btl5F6UrkBoJJaDQzke1VvVN', name='get_customer_info', type='function_call', id='fc_080cc194cfa17c94006943fcf82ba08194a65b676e302e9aa6', status='completed')]</code></pre>
</div>
<div class="cell-output cell-output-display">
<pre><code>ResponseFunctionToolCall(arguments='{"customer_id":"C1"}', call_id='call_Btl5F6UrkBoJJaDQzke1VvVN', name='get_customer_info', type='function_call', id='fc_080cc194cfa17c94006943fcf82ba08194a65b676e302e9aa6', status='completed')</code></pre>
</div>
<div class="cell-output cell-output-display">
<pre><code>{'type': 'function_call_output',
 'call_id': 'call_Btl5F6UrkBoJJaDQzke1VvVN',
 'output': "{'name': 'John Doe', 'email': 'john@example.com', 'phone': '123-456-7890', 'orders': [{'id': 'O1', 'product': 'Widget A', 'quantity': 2, 'price': 19.99, 'status': 'Shipped'}, {'id': 'O2', 'product': 'Gadget B', 'quantity': 1, 'price': 49.99, 'status': 'Processing'}]}"}</code></pre>
</div>
<div class="cell-output cell-output-display">
<pre><code>[ResponseReasoningItem(id='rs_080cc194cfa17c94006943fcf913188194ab017b95ba08a13e', summary=[], type='reasoning', content=None, encrypted_content=None, status=None),
 ResponseFunctionToolCall(arguments='{"order_id":"O1"}', call_id='call_4yaVagsUWe86YMk25kyCU9x2', name='cancel_order', type='function_call', id='fc_080cc194cfa17c94006943fcfa8bd081949731f7da8c5adc86', status='completed'),
 ResponseFunctionToolCall(arguments='{"order_id":"O2"}', call_id='call_Vy0mCP8ocOYR31qk4sbVgRw5', name='cancel_order', type='function_call', id='fc_080cc194cfa17c94006943fcfab9688194a97ce8bb7ff46706', status='completed')]</code></pre>
</div>
<div class="cell-output cell-output-display">
<pre><code>ResponseFunctionToolCall(arguments='{"order_id":"O1"}', call_id='call_4yaVagsUWe86YMk25kyCU9x2', name='cancel_order', type='function_call', id='fc_080cc194cfa17c94006943fcfa8bd081949731f7da8c5adc86', status='completed')</code></pre>
</div>
<div class="cell-output cell-output-display">
<pre><code>ResponseFunctionToolCall(arguments='{"order_id":"O2"}', call_id='call_Vy0mCP8ocOYR31qk4sbVgRw5', name='cancel_order', type='function_call', id='fc_080cc194cfa17c94006943fcfab9688194a97ce8bb7ff46706', status='completed')</code></pre>
</div>
<div class="cell-output cell-output-display">
<pre><code>{'type': 'function_call_output',
 'call_id': 'call_4yaVagsUWe86YMk25kyCU9x2',
 'output': 'True'}</code></pre>
</div>
<div class="cell-output cell-output-display">
<pre><code>{'type': 'function_call_output',
 'call_id': 'call_Vy0mCP8ocOYR31qk4sbVgRw5',
 'output': 'True'}</code></pre>
</div>
<div class="cell-output cell-output-display">
<pre><code>[ResponseReasoningItem(id='rs_080cc194cfa17c94006943fcfbd120819490c3ad1d75350865', summary=[], type='reasoning', content=None, encrypted_content=None, status=None),
 ResponseOutputMessage(id='msg_080cc194cfa17c94006943fd043f948194ad1bb58d51d2de71', content=[ResponseOutputText(annotations=[], text='Done — I canceled all orders for customer C1 (John Doe).\n\nSummary:\n- O1 — Widget A — previous status: Shipped — cancellation: Success\n- O2 — Gadget B — previous status: Processing — cancellation: Success\n\nWould you like me to check refund status, send a confirmation to john@example.com, or do anything else?', type='output_text', logprobs=[])], role='assistant', status='completed', type='message')]</code></pre>
</div>
<div class="cell-output cell-output-display">
<pre><code>ResponseOutputMessage(id='msg_080cc194cfa17c94006943fd043f948194ad1bb58d51d2de71', content=[ResponseOutputText(annotations=[], text='Done — I canceled all orders for customer C1 (John Doe).\n\nSummary:\n- O1 — Widget A — previous status: Shipped — cancellation: Success\n- O2 — Gadget B — previous status: Processing — cancellation: Success\n\nWould you like me to check refund status, send a confirmation to john@example.com, or do anything else?', type='output_text', logprobs=[])], role='assistant', status='completed', type='message')</code></pre>
</div>
</div>
<div id="5b8a9d4c" class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb57"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="co"># cl = loop_outputs(res)</span></span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Markdown('\n'.join(map(disp_tc, cl)))</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div id="2421d39d" class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb58"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> o <span class="kw">in</span> chat.toolloop(<span class="st">'What is the status of order O2?'</span>): display(o)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>- Retrieving order O2</code></pre>
</div>
<div class="cell-output cell-output-display cell-output-markdown">
<ul>
<li>id: resp_080cc194cfa17c94006943fd06606c8194acbf56e9291c70ca</li>
<li>created_at: 1766063366.0</li>
<li>error: None</li>
<li>incomplete_details: None</li>
<li>instructions: None</li>
<li>metadata: {}</li>
<li>model: gpt-5-mini-2025-08-07</li>
<li>object: response</li>
<li>output: [ResponseReasoningItem(id=‘rs_080cc194cfa17c94006943fd06bbd4819499041c0e2a896d43’, summary=[], type=‘reasoning’, content=None, encrypted_content=None, status=None), ResponseFunctionToolCall(arguments=‘{“order_id”:“O2”}’, call_id=‘call_47iqPnLAFKxbJ4JJ9EQwWw71’, name=‘get_order_details’, type=‘function_call’, id=‘fc_080cc194cfa17c94006943fd07c3308194a643843cb1720a9e’, status=‘completed’)]</li>
<li>parallel_tool_calls: True</li>
<li>temperature: 1.0</li>
<li>tool_choice: auto</li>
<li>tools: [FunctionTool(name=‘get_customer_info’, parameters={‘type’: ‘object’, ‘properties’: {‘customer_id’: {‘type’: ‘string’, ‘description’: ‘ID of the customer’}}, ‘required’: [‘customer_id’], ‘additionalProperties’: False}, strict=True, type=‘function’, description=“Retrieves a customer’s information and their orders based on the customer ID”), FunctionTool(name=‘get_order_details’, parameters={‘type’: ‘object’, ‘properties’: {‘order_id’: {‘type’: ‘string’, ‘description’: ‘ID of the order’}}, ‘required’: [‘order_id’], ‘additionalProperties’: False}, strict=True, type=‘function’, description=‘Retrieves the details of a specific order based on the order ID’), FunctionTool(name=‘cancel_order’, parameters={‘type’: ‘object’, ‘properties’: {‘order_id’: {‘type’: ‘string’, ‘description’: ‘ID of the order to cancel’}}, ‘required’: [‘order_id’], ‘additionalProperties’: False}, strict=True, type=‘function’, description=‘Cancels an order based on the provided order ID:- type: boolean’)]</li>
<li>top_p: 1.0</li>
<li>background: False</li>
<li>conversation: None</li>
<li>max_output_tokens: 4096</li>
<li>max_tool_calls: None</li>
<li>previous_response_id: None</li>
<li>prompt: None</li>
<li>prompt_cache_key: None</li>
<li>prompt_cache_retention: None</li>
<li>reasoning: Reasoning(effort=‘medium’, generate_summary=None, summary=None)</li>
<li>safety_identifier: None</li>
<li>service_tier: default</li>
<li>status: completed</li>
<li>text: ResponseTextConfig(format=ResponseFormatText(type=‘text’), verbosity=‘medium’)</li>
<li>top_logprobs: 0</li>
<li>truncation: disabled</li>
<li>usage: ResponseUsage(input_tokens=521, input_tokens_details=InputTokensDetails(cached_tokens=0), output_tokens=87, output_tokens_details=OutputTokensDetails(reasoning_tokens=64), total_tokens=608)</li>
<li>user: None</li>
<li>billing: {‘payer’: ‘openai’}</li>
<li>store: True</li>
</ul>
</div>
<div class="cell-output cell-output-display">
<pre><code>ResponseFunctionToolCall(arguments='{"order_id":"O2"}', call_id='call_47iqPnLAFKxbJ4JJ9EQwWw71', name='get_order_details', type='function_call', id='fc_080cc194cfa17c94006943fd07c3308194a643843cb1720a9e', status='completed')</code></pre>
</div>
<div class="cell-output cell-output-display">
<pre><code>{'type': 'function_call_output',
 'call_id': 'call_47iqPnLAFKxbJ4JJ9EQwWw71',
 'output': "{'id': 'O2', 'product': 'Gadget B', 'quantity': 1, 'price': 49.99, 'status': 'Cancelled'}"}</code></pre>
</div>
<div class="cell-output cell-output-display cell-output-markdown">
<p>Order O2 is now: Cancelled.</p>
<details>
<ul>
<li>id: resp_080cc194cfa17c94006943fd0841e88194b12aa8c8f30b4e64</li>
<li>created_at: 1766063368.0</li>
<li>error: None</li>
<li>incomplete_details: None</li>
<li>instructions: None</li>
<li>metadata: {}</li>
<li>model: gpt-5-mini-2025-08-07</li>
<li>object: response</li>
<li>output: [ResponseOutputMessage(id=‘msg_080cc194cfa17c94006943fd08ad488194a093653ee36021db’, content=[ResponseOutputText(annotations=[], text=‘Order O2 is now: Cancelled.’, type=‘output_text’, logprobs=[])], role=‘assistant’, status=‘completed’, type=‘message’)]</li>
<li>parallel_tool_calls: True</li>
<li>temperature: 1.0</li>
<li>tool_choice: auto</li>
<li>tools: [FunctionTool(name=‘get_customer_info’, parameters={‘type’: ‘object’, ‘properties’: {‘customer_id’: {‘type’: ‘string’, ‘description’: ‘ID of the customer’}}, ‘required’: [‘customer_id’], ‘additionalProperties’: False}, strict=True, type=‘function’, description=“Retrieves a customer’s information and their orders based on the customer ID”), FunctionTool(name=‘get_order_details’, parameters={‘type’: ‘object’, ‘properties’: {‘order_id’: {‘type’: ‘string’, ‘description’: ‘ID of the order’}}, ‘required’: [‘order_id’], ‘additionalProperties’: False}, strict=True, type=‘function’, description=‘Retrieves the details of a specific order based on the order ID’), FunctionTool(name=‘cancel_order’, parameters={‘type’: ‘object’, ‘properties’: {‘order_id’: {‘type’: ‘string’, ‘description’: ‘ID of the order to cancel’}}, ‘required’: [‘order_id’], ‘additionalProperties’: False}, strict=True, type=‘function’, description=‘Cancels an order based on the provided order ID:- type: boolean’)]</li>
<li>top_p: 1.0</li>
<li>background: False</li>
<li>conversation: None</li>
<li>max_output_tokens: 4096</li>
<li>max_tool_calls: None</li>
<li>previous_response_id: None</li>
<li>prompt: None</li>
<li>prompt_cache_key: None</li>
<li>prompt_cache_retention: None</li>
<li>reasoning: Reasoning(effort=‘medium’, generate_summary=None, summary=None)</li>
<li>safety_identifier: None</li>
<li>service_tier: default</li>
<li>status: completed</li>
<li>text: ResponseTextConfig(format=ResponseFormatText(type=‘text’), verbosity=‘medium’)</li>
<li>top_logprobs: 0</li>
<li>truncation: disabled</li>
<li>usage: ResponseUsage(input_tokens=676, input_tokens_details=InputTokensDetails(cached_tokens=0), output_tokens=13, output_tokens_details=OutputTokensDetails(reasoning_tokens=0), total_tokens=689)</li>
<li>user: None</li>
<li>billing: {‘payer’: ‘openai’}</li>
<li>store: True</li>
</ul>
</details>
</div>
</div>
</section>
<section id="test-math-example" class="level3">
<h3 class="anchored" data-anchor-id="test-math-example">Test Math Example</h3>
<div id="0fd52dbc" class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb62"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> add(x: <span class="bu">int</span>, y: <span class="bu">int</span>) <span class="op">-&gt;</span> <span class="bu">int</span>:</span>
<span id="cb62-2"><a href="#cb62-2" aria-hidden="true" tabindex="-1"></a>    <span class="co">"adds x and y."</span></span>
<span id="cb62-3"><a href="#cb62-3" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> x <span class="op">+</span> y</span>
<span id="cb62-4"><a href="#cb62-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-5"><a href="#cb62-5" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> mul(x: <span class="bu">int</span>, y: <span class="bu">int</span>) <span class="op">-&gt;</span> <span class="bu">int</span>:</span>
<span id="cb62-6"><a href="#cb62-6" aria-hidden="true" tabindex="-1"></a>    <span class="co">"multiplies x and y."</span></span>
<span id="cb62-7"><a href="#cb62-7" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> x <span class="op">*</span> y</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div id="c1cc19bf" class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb63"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a>chat <span class="op">=</span> Chat(model, tools<span class="op">=</span>[add, mul], <span class="op">**</span>chatkw)</span>
<span id="cb63-2"><a href="#cb63-2" aria-hidden="true" tabindex="-1"></a>pr <span class="op">=</span> <span class="st">'Can you add 1258585825128 to 34959234595, multiply by 93, and then add (-12439149)?'</span></span>
<span id="cb63-3"><a href="#cb63-3" aria-hidden="true" tabindex="-1"></a>r <span class="op">=</span> chat.toolloop(pr)</span>
<span id="cb63-4"><a href="#cb63-4" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> o <span class="kw">in</span> r: show(o)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<pre><code>[ResponseReasoningItem(id='rs_02621606c3b513dc006943fd09ad40819781fb7b32d5e5996a', summary=[], type='reasoning', content=None, encrypted_content=None, status=None),
 ResponseFunctionToolCall(arguments='{"x":1258585825128,"y":34959234595}', call_id='call_Fg3v2kfgWIogSl1IEB0w1Y0K', name='add', type='function_call', id='fc_02621606c3b513dc006943fd09fdf881979ba71de45af8d588', status='completed')]</code></pre>
</div>
<div class="cell-output cell-output-display">
<pre><code>ResponseFunctionToolCall(arguments='{"x":1258585825128,"y":34959234595}', call_id='call_Fg3v2kfgWIogSl1IEB0w1Y0K', name='add', type='function_call', id='fc_02621606c3b513dc006943fd09fdf881979ba71de45af8d588', status='completed')</code></pre>
</div>
<div class="cell-output cell-output-display">
<pre><code>{'type': 'function_call_output',
 'call_id': 'call_Fg3v2kfgWIogSl1IEB0w1Y0K',
 'output': '1293545059723'}</code></pre>
</div>
<div class="cell-output cell-output-display">
<pre><code>[ResponseFunctionToolCall(arguments='{"x":1293545059723,"y":93}', call_id='call_9rimpAnaVInF4ssbHosAfTi8', name='mul', type='function_call', id='fc_02621606c3b513dc006943fd0bae9c81978026c7bfaae4a759', status='completed')]</code></pre>
</div>
<div class="cell-output cell-output-display">
<pre><code>{'type': 'function_call_output',
 'call_id': 'call_9rimpAnaVInF4ssbHosAfTi8',
 'output': '120299690554239'}</code></pre>
</div>
<div class="cell-output cell-output-display">
<pre><code>[ResponseFunctionToolCall(arguments='{"x":120299690554239,"y":-12439149}', call_id='call_OS43dlWKEYtYAocZpHJ94RXM', name='add', type='function_call', id='fc_02621606c3b513dc006943fd0c9f5c8197a11bc188b0174d6d', status='completed')]</code></pre>
</div>
<div class="cell-output cell-output-display">
<pre><code>{'type': 'function_call_output',
 'call_id': 'call_OS43dlWKEYtYAocZpHJ94RXM',
 'output': '120299678115090'}</code></pre>
</div>
<div class="cell-output cell-output-display cell-output-markdown">
<p>120299678115090</p>
<details>
<ul>
<li>id: resp_02621606c3b513dc006943fd0d30f48197a911787dca9e5d00</li>
<li>created_at: 1766063373.0</li>
<li>error: None</li>
<li>incomplete_details: None</li>
<li>instructions: None</li>
<li>metadata: {}</li>
<li>model: gpt-5-mini-2025-08-07</li>
<li>object: response</li>
<li>output: [ResponseOutputMessage(id=‘msg_02621606c3b513dc006943fd0d80f88197b58e845951e295e1’, content=[ResponseOutputText(annotations=[], text=‘120299678115090’, type=‘output_text’, logprobs=[])], role=‘assistant’, status=‘completed’, type=‘message’)]</li>
<li>parallel_tool_calls: True</li>
<li>temperature: 1.0</li>
<li>tool_choice: auto</li>
<li>tools: [FunctionTool(name=‘add’, parameters={‘type’: ‘object’, ‘properties’: {‘x’: {‘type’: ‘integer’, ‘description’: ’‘}, ’y’: {‘type’: ‘integer’, ‘description’: ’‘}}, ’required’: [‘x’, ‘y’], ‘additionalProperties’: False}, strict=True, type=‘function’, description=‘adds x and y.:- type: integer’), FunctionTool(name=‘mul’, parameters={‘type’: ‘object’, ‘properties’: {‘x’: {‘type’: ‘integer’, ‘description’: ’‘}, ’y’: {‘type’: ‘integer’, ‘description’: ’‘}}, ’required’: [‘x’, ‘y’], ‘additionalProperties’: False}, strict=True, type=‘function’, description=‘multiplies x and y.:- type: integer’)]</li>
<li>top_p: 1.0</li>
<li>background: False</li>
<li>conversation: None</li>
<li>max_output_tokens: 4096</li>
<li>max_tool_calls: None</li>
<li>previous_response_id: None</li>
<li>prompt: None</li>
<li>prompt_cache_key: None</li>
<li>prompt_cache_retention: None</li>
<li>reasoning: Reasoning(effort=‘minimal’, generate_summary=None, summary=None)</li>
<li>safety_identifier: None</li>
<li>service_tier: default</li>
<li>status: completed</li>
<li>text: ResponseTextConfig(format=ResponseFormatText(type=‘text’), verbosity=‘low’)</li>
<li>top_logprobs: 0</li>
<li>truncation: disabled</li>
<li>usage: ResponseUsage(input_tokens=250, input_tokens_details=InputTokensDetails(cached_tokens=0), output_tokens=9, output_tokens_details=OutputTokensDetails(reasoning_tokens=0), total_tokens=259)</li>
<li>user: None</li>
<li>billing: {‘payer’: ‘openai’}</li>
<li>store: True</li>
</ul>
</details>
</div>
</div>
<div id="5fdc44e8" class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb71"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a>(<span class="dv">1258585825128</span> <span class="op">+</span> <span class="dv">34959234595</span>) <span class="op">*</span> <span class="dv">93</span> <span class="op">-</span> <span class="dv">12439149</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<pre><code>120299678115090</code></pre>
</div>
</div>
<div id="62be2307" class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb73"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a>chat <span class="op">=</span> Chat(model, tools<span class="op">=</span>[add, mul], <span class="op">**</span>chatkw)</span>
<span id="cb73-2"><a href="#cb73-2" aria-hidden="true" tabindex="-1"></a>r <span class="op">=</span> chat.toolloop(pr, stream<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb73-3"><a href="#cb73-3" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> o <span class="kw">in</span> r:</span>
<span id="cb73-4"><a href="#cb73-4" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> <span class="bu">isinstance</span>(o, <span class="bu">dict</span>): <span class="bu">print</span>(<span class="st">'- '</span>, o)</span>
<span id="cb73-5"><a href="#cb73-5" aria-hidden="true" tabindex="-1"></a>    <span class="cf">else</span>:</span>
<span id="cb73-6"><a href="#cb73-6" aria-hidden="true" tabindex="-1"></a>        <span class="cf">for</span> p <span class="kw">in</span> o: <span class="bu">print</span>(p, end<span class="op">=</span><span class="st">''</span>)</span>
<span id="cb73-7"><a href="#cb73-7" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> <span class="bu">hasattr</span>(o, <span class="st">'value'</span>): show(o.value)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<pre><code>[ResponseReasoningItem(id='rs_0944024f48105103006943fd116be8819483df3a9f25e3d328', summary=[], type='reasoning', content=None, encrypted_content=None, status=None),
 ResponseFunctionToolCall(arguments='{"x":1258585825128,"y":34959234595}', call_id='call_B6xGJDpQJm5GrS2hnngybWTe', name='add', type='function_call', id='fc_0944024f48105103006943fd11abcc81949200a4eabf12e97b', status='completed')]</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>('arguments', '{"x":1258585825128,"y":34959234595}')('call_id', 'call_B6xGJDpQJm5GrS2hnngybWTe')('name', 'add')('type', 'function_call')('id', 'fc_0944024f48105103006943fd11abcc81949200a4eabf12e97b')('status', 'completed')-  {'type': 'function_call_output', 'call_id': 'call_B6xGJDpQJm5GrS2hnngybWTe', 'output': '1293545059723'}</code></pre>
</div>
<div class="cell-output cell-output-display">
<pre><code>[ResponseFunctionToolCall(arguments='{"x":1293545059723,"y":93}', call_id='call_Vb3v1awZxvoZuUjbq9RRZrfM', name='mul', type='function_call', id='fc_0944024f48105103006943fd1402188194a2adccf222c76591', status='completed')]</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>-  {'type': 'function_call_output', 'call_id': 'call_Vb3v1awZxvoZuUjbq9RRZrfM', 'output': '120299690554239'}</code></pre>
</div>
<div class="cell-output cell-output-display">
<pre><code>[ResponseFunctionToolCall(arguments='{"x":120299690554239,"y":-12439149}', call_id='call_Dd1Uzt8rMfWJCH0irbMa5OVV', name='add', type='function_call', id='fc_0944024f48105103006943fd14e54481948906bd955b405418', status='completed')]</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>-  {'type': 'function_call_output', 'call_id': 'call_Dd1Uzt8rMfWJCH0irbMa5OVV', 'output': '120299678115090'}
120299678115090</code></pre>
</div>
<div class="cell-output cell-output-display cell-output-markdown">
<p>120299678115090</p>
<details>
<ul>
<li>id: resp_0944024f48105103006943fd1583ec8194863012f06a95bb9a</li>
<li>created_at: 1766063381.0</li>
<li>error: None</li>
<li>incomplete_details: None</li>
<li>instructions: None</li>
<li>metadata: {}</li>
<li>model: gpt-5-mini-2025-08-07</li>
<li>object: response</li>
<li>output: [ResponseOutputMessage(id=‘msg_0944024f48105103006943fd16463c81949df34dd0158af4c1’, content=[ResponseOutputText(annotations=[], text=‘120299678115090’, type=‘output_text’, logprobs=[])], role=‘assistant’, status=‘completed’, type=‘message’)]</li>
<li>parallel_tool_calls: True</li>
<li>temperature: 1.0</li>
<li>tool_choice: auto</li>
<li>tools: [FunctionTool(name=‘add’, parameters={‘type’: ‘object’, ‘properties’: {‘x’: {‘type’: ‘integer’, ‘description’: ’‘}, ’y’: {‘type’: ‘integer’, ‘description’: ’‘}}, ’required’: [‘x’, ‘y’], ‘additionalProperties’: False}, strict=True, type=‘function’, description=‘adds x and y.:- type: integer’), FunctionTool(name=‘mul’, parameters={‘type’: ‘object’, ‘properties’: {‘x’: {‘type’: ‘integer’, ‘description’: ’‘}, ’y’: {‘type’: ‘integer’, ‘description’: ’‘}}, ’required’: [‘x’, ‘y’], ‘additionalProperties’: False}, strict=True, type=‘function’, description=‘multiplies x and y.:- type: integer’)]</li>
<li>top_p: 1.0</li>
<li>background: False</li>
<li>conversation: None</li>
<li>max_output_tokens: 4096</li>
<li>max_tool_calls: None</li>
<li>previous_response_id: None</li>
<li>prompt: None</li>
<li>prompt_cache_key: None</li>
<li>prompt_cache_retention: None</li>
<li>reasoning: Reasoning(effort=‘minimal’, generate_summary=None, summary=None)</li>
<li>safety_identifier: None</li>
<li>service_tier: default</li>
<li>status: completed</li>
<li>text: ResponseTextConfig(format=ResponseFormatText(type=‘text’), verbosity=‘low’)</li>
<li>top_logprobs: 0</li>
<li>truncation: disabled</li>
<li>usage: ResponseUsage(input_tokens=250, input_tokens_details=InputTokensDetails(cached_tokens=0), output_tokens=9, output_tokens_details=OutputTokensDetails(reasoning_tokens=0), total_tokens=259)</li>
<li>user: None</li>
<li>store: True</li>
</ul>
</details>
</div>
</div>
</section>
<section id="error-conditions-out-of-iterations-exception-during-tool-invocation" class="level3">
<h3 class="anchored" data-anchor-id="error-conditions-out-of-iterations-exception-during-tool-invocation">Error Conditions: Out of Iterations, Exception During Tool Invocation</h3>
<div id="82c63e59" class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb80"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb80-1"><a href="#cb80-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> mydiv(a:<span class="bu">float</span>, b:<span class="bu">float</span>):</span>
<span id="cb80-2"><a href="#cb80-2" aria-hidden="true" tabindex="-1"></a>    <span class="co">"Divide two numbers"</span></span>
<span id="cb80-3"><a href="#cb80-3" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> a <span class="op">/</span> b</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div id="26bc1bd9" class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb81"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb81-1"><a href="#cb81-1" aria-hidden="true" tabindex="-1"></a>chat <span class="op">=</span> Chat(model, tools<span class="op">=</span>[mydiv], <span class="op">**</span>chatkw)</span>
<span id="cb81-2"><a href="#cb81-2" aria-hidden="true" tabindex="-1"></a>r <span class="op">=</span> chat.toolloop(<span class="st">'Please calculate this sequence using your tools: 43/23454; 652/previous result; 6843/previous result; 321/previous result'</span>, max_steps<span class="op">=</span><span class="dv">2</span>)</span>
<span id="cb81-3"><a href="#cb81-3" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> o <span class="kw">in</span> r: show(o)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<pre><code>[ResponseReasoningItem(id='rs_02f9e0725e9fb6a5006943fd16f3dc81979a3aa89dfcb98aca', summary=[], type='reasoning', content=None, encrypted_content=None, status=None),
 ResponseFunctionToolCall(arguments='{"a":43,"b":23454}', call_id='call_Fnsc5iNP8rMuj0rqeBLzXVsO', name='mydiv', type='function_call', id='fc_02f9e0725e9fb6a5006943fd177c6c8197a5ad34f31755933a', status='completed'),
 ResponseFunctionToolCall(arguments='{"a":652,"b":0}', call_id='call_k7APDmfK4dy57LeiHYhBCNq6', name='mydiv', type='function_call', id='fc_02f9e0725e9fb6a5006943fd17b4d08197ada7efed9792c679', status='completed'),
 ResponseFunctionToolCall(arguments='{"a":6843,"b":0}', call_id='call_ZpzLBH2zM3Wcy9aoFCbnZ0mN', name='mydiv', type='function_call', id='fc_02f9e0725e9fb6a5006943fd17e5bc8197b3e6f2903db6ce9d', status='completed'),
 ResponseFunctionToolCall(arguments='{"a":321,"b":0}', call_id='call_JGS2KeOU7ku3n56kqbSrvEGy', name='mydiv', type='function_call', id='fc_02f9e0725e9fb6a5006943fd181dd88197bd6492c3465327ea', status='completed')]</code></pre>
</div>
<div class="cell-output cell-output-display">
<pre><code>ResponseFunctionToolCall(arguments='{"a":43,"b":23454}', call_id='call_Fnsc5iNP8rMuj0rqeBLzXVsO', name='mydiv', type='function_call', id='fc_02f9e0725e9fb6a5006943fd177c6c8197a5ad34f31755933a', status='completed')</code></pre>
</div>
<div class="cell-output cell-output-display">
<pre><code>ResponseFunctionToolCall(arguments='{"a":652,"b":0}', call_id='call_k7APDmfK4dy57LeiHYhBCNq6', name='mydiv', type='function_call', id='fc_02f9e0725e9fb6a5006943fd17b4d08197ada7efed9792c679', status='completed')</code></pre>
</div>
<div class="cell-output cell-output-display">
<pre><code>ResponseFunctionToolCall(arguments='{"a":6843,"b":0}', call_id='call_ZpzLBH2zM3Wcy9aoFCbnZ0mN', name='mydiv', type='function_call', id='fc_02f9e0725e9fb6a5006943fd17e5bc8197b3e6f2903db6ce9d', status='completed')</code></pre>
</div>
<div class="cell-output cell-output-display">
<pre><code>ResponseFunctionToolCall(arguments='{"a":321,"b":0}', call_id='call_JGS2KeOU7ku3n56kqbSrvEGy', name='mydiv', type='function_call', id='fc_02f9e0725e9fb6a5006943fd181dd88197bd6492c3465327ea', status='completed')</code></pre>
</div>
<div class="cell-output cell-output-display">
<pre><code>{'type': 'function_call_output',
 'call_id': 'call_Fnsc5iNP8rMuj0rqeBLzXVsO',
 'output': '0.001833375969983798'}</code></pre>
</div>
<div class="cell-output cell-output-display">
<pre><code>{'type': 'function_call_output',
 'call_id': 'call_k7APDmfK4dy57LeiHYhBCNq6',
 'output': 'Traceback (most recent call last):\n  File "/usr/local/lib/python3.12/site-packages/toolslm/funccall.py", line 215, in call_func\n    try: return func(**inps)\n                ^^^^^^^^^^^^\n  File "/tmp/ipykernel_5385/246724137.py", line 3, in mydiv\n    return a / b\n           ~~^~~\nZeroDivisionError: division by zero\n'}</code></pre>
</div>
<div class="cell-output cell-output-display">
<pre><code>{'type': 'function_call_output',
 'call_id': 'call_ZpzLBH2zM3Wcy9aoFCbnZ0mN',
 'output': 'Traceback (most recent call last):\n  File "/usr/local/lib/python3.12/site-packages/toolslm/funccall.py", line 215, in call_func\n    try: return func(**inps)\n                ^^^^^^^^^^^^\n  File "/tmp/ipykernel_5385/246724137.py", line 3, in mydiv\n    return a / b\n           ~~^~~\nZeroDivisionError: division by zero\n'}</code></pre>
</div>
<div class="cell-output cell-output-display">
<pre><code>{'type': 'function_call_output',
 'call_id': 'call_JGS2KeOU7ku3n56kqbSrvEGy',
 'output': 'Traceback (most recent call last):\n  File "/usr/local/lib/python3.12/site-packages/toolslm/funccall.py", line 215, in call_func\n    try: return func(**inps)\n                ^^^^^^^^^^^^\n  File "/tmp/ipykernel_5385/246724137.py", line 3, in mydiv\n    return a / b\n           ~~^~~\nZeroDivisionError: division by zero\n'}</code></pre>
</div>
<div class="cell-output cell-output-display cell-output-markdown">
<p>I computed the first division successfully: - 43 / 23454 = 0.001833375969983798</p>
<p>I attempted the next steps but they failed because I tried to divide by zero (I passed 0 as the “previous result” for subsequent operations), causing errors. To complete the sequence you want, I need to perform these successive calculations using the preceding result each time: 1. 652 / (43/23454) 2. 6843 / (result of step 2) 3. 321 / (result of step 3)</p>
<p>If you want, I can now: - Recompute the chain without tool limits and give all four results, or - Compute them step-by-step here directly (no tools needed). Which do you prefer?</p>
<details>
<ul>
<li>id: resp_02f9e0725e9fb6a5006943fd18bff081979e13bb5930ee32b7</li>
<li>created_at: 1766063384.0</li>
<li>error: None</li>
<li>incomplete_details: None</li>
<li>instructions: None</li>
<li>metadata: {}</li>
<li>model: gpt-5-mini-2025-08-07</li>
<li>object: response</li>
<li>output: [ResponseReasoningItem(id=‘rs_02f9e0725e9fb6a5006943fd19334c8197b4b20beb1ae09493’, summary=[], type=‘reasoning’, content=None, encrypted_content=None, status=None), ResponseOutputMessage(id=‘msg_02f9e0725e9fb6a5006943fd195a9c81978fb9bcca07f80c87’, content=[ResponseOutputText(annotations=[], text=‘I computed the first division successfully:- 43 / 23454 = 0.001833375969983798attempted the next steps but they failed because I tried to divide by zero (I passed 0 as the “previous result” for subsequent operations), causing errors. To complete the sequence you want, I need to perform these successive calculations using the preceding result each time:. 652 / (43/23454). 6843 / (result of step 2). 321 / (result of step 3)you want, I can now:- Recompute the chain without tool limits and give all four results, or- Compute them step-by-step here directly (no tools needed). Which do you prefer?’, type=‘output_text’, logprobs=[])], role=‘assistant’, status=‘completed’, type=‘message’)]</li>
<li>parallel_tool_calls: True</li>
<li>temperature: 1.0</li>
<li>tool_choice: auto</li>
<li>tools: [FunctionTool(name=‘mydiv’, parameters={‘type’: ‘object’, ‘properties’: {‘a’: {‘type’: ‘number’, ‘description’: ’‘}, ’b’: {‘type’: ‘number’, ‘description’: ’‘}}, ’required’: [‘a’, ‘b’], ‘additionalProperties’: False}, strict=True, type=‘function’, description=‘Divide two numbers’)]</li>
<li>top_p: 1.0</li>
<li>background: False</li>
<li>conversation: None</li>
<li>max_output_tokens: 4096</li>
<li>max_tool_calls: None</li>
<li>previous_response_id: None</li>
<li>prompt: None</li>
<li>prompt_cache_key: None</li>
<li>prompt_cache_retention: None</li>
<li>reasoning: Reasoning(effort=‘minimal’, generate_summary=None, summary=None)</li>
<li>safety_identifier: None</li>
<li>service_tier: default</li>
<li>status: completed</li>
<li>text: ResponseTextConfig(format=ResponseFormatText(type=‘text’), verbosity=‘low’)</li>
<li>top_logprobs: 0</li>
<li>truncation: disabled</li>
<li>usage: ResponseUsage(input_tokens=537, input_tokens_details=InputTokensDetails(cached_tokens=0), output_tokens=163, output_tokens_details=OutputTokensDetails(reasoning_tokens=0), total_tokens=700)</li>
<li>user: None</li>
<li>billing: {‘payer’: ‘openai’}</li>
<li>store: True</li>
</ul>
</details>
</div>
<div class="cell-output cell-output-display">
<pre><code>ResponseOutputMessage(id='msg_02f9e0725e9fb6a5006943fd195a9c81978fb9bcca07f80c87', content=[ResponseOutputText(annotations=[], text='I computed the first division successfully:\n- 43 / 23454 = 0.001833375969983798\n\nI attempted the next steps but they failed because I tried to divide by zero (I passed 0 as the “previous result” for subsequent operations), causing errors. To complete the sequence you want, I need to perform these successive calculations using the preceding result each time:\n1. 652 / (43/23454)\n2. 6843 / (result of step 2)\n3. 321 / (result of step 3)\n\nIf you want, I can now:\n- Recompute the chain without tool limits and give all four results, or\n- Compute them step-by-step here directly (no tools needed). Which do you prefer?', type='output_text', logprobs=[])], role='assistant', status='completed', type='message')</code></pre>
</div>
</div>
<p>This tests <code>raise_on_err=False</code> change to <code>toolslm.call_func</code> invocation. We should see this return an error as a string instead of crash:</p>
<div id="730cbb2c" class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb92"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb92-1"><a href="#cb92-1" aria-hidden="true" tabindex="-1"></a>chat <span class="op">=</span> Chat(model, tools<span class="op">=</span>[mydiv], <span class="op">**</span>chatkw)</span>
<span id="cb92-2"><a href="#cb92-2" aria-hidden="true" tabindex="-1"></a>r <span class="op">=</span> chat.toolloop(<span class="st">'Try dividing 1 by 0 and see what the error result is'</span>)</span>
<span id="cb92-3"><a href="#cb92-3" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> o <span class="kw">in</span> r: show(o)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<pre><code>[ResponseReasoningItem(id='rs_0af57bb05fb6f746006943fd1bd07c81958a319ad4cb70eae8', summary=[], type='reasoning', content=None, encrypted_content=None, status=None),
 ResponseFunctionToolCall(arguments='{"a":1,"b":0}', call_id='call_0FGtqnXi4rLuPC0ivZcaRw24', name='mydiv', type='function_call', id='fc_0af57bb05fb6f746006943fd1c29a08195989bf0c4f670baca', status='completed')]</code></pre>
</div>
<div class="cell-output cell-output-display">
<pre><code>ResponseFunctionToolCall(arguments='{"a":1,"b":0}', call_id='call_0FGtqnXi4rLuPC0ivZcaRw24', name='mydiv', type='function_call', id='fc_0af57bb05fb6f746006943fd1c29a08195989bf0c4f670baca', status='completed')</code></pre>
</div>
<div class="cell-output cell-output-display">
<pre><code>{'type': 'function_call_output',
 'call_id': 'call_0FGtqnXi4rLuPC0ivZcaRw24',
 'output': 'Traceback (most recent call last):\n  File "/usr/local/lib/python3.12/site-packages/toolslm/funccall.py", line 215, in call_func\n    try: return func(**inps)\n                ^^^^^^^^^^^^\n  File "/tmp/ipykernel_5385/246724137.py", line 3, in mydiv\n    return a / b\n           ~~^~~\nZeroDivisionError: division by zero\n'}</code></pre>
</div>
<div class="cell-output cell-output-display cell-output-markdown">
<p>ZeroDivisionError: division by zero</p>
<details>
<ul>
<li>id: resp_0af57bb05fb6f746006943fd1cbdac8195b5d480c66c146b06</li>
<li>created_at: 1766063388.0</li>
<li>error: None</li>
<li>incomplete_details: None</li>
<li>instructions: None</li>
<li>metadata: {}</li>
<li>model: gpt-5-mini-2025-08-07</li>
<li>object: response</li>
<li>output: [ResponseOutputMessage(id=‘msg_0af57bb05fb6f746006943fd1d335881958929318eb6ad6c40’, content=[ResponseOutputText(annotations=[], text=‘ZeroDivisionError: division by zero’, type=‘output_text’, logprobs=[])], role=‘assistant’, status=‘completed’, type=‘message’)]</li>
<li>parallel_tool_calls: True</li>
<li>temperature: 1.0</li>
<li>tool_choice: auto</li>
<li>tools: [FunctionTool(name=‘mydiv’, parameters={‘type’: ‘object’, ‘properties’: {‘a’: {‘type’: ‘number’, ‘description’: ’‘}, ’b’: {‘type’: ‘number’, ‘description’: ’‘}}, ’required’: [‘a’, ‘b’], ‘additionalProperties’: False}, strict=True, type=‘function’, description=‘Divide two numbers’)]</li>
<li>top_p: 1.0</li>
<li>background: False</li>
<li>conversation: None</li>
<li>max_output_tokens: 4096</li>
<li>max_tool_calls: None</li>
<li>previous_response_id: None</li>
<li>prompt: None</li>
<li>prompt_cache_key: None</li>
<li>prompt_cache_retention: None</li>
<li>reasoning: Reasoning(effort=‘minimal’, generate_summary=None, summary=None)</li>
<li>safety_identifier: None</li>
<li>service_tier: default</li>
<li>status: completed</li>
<li>text: ResponseTextConfig(format=ResponseFormatText(type=‘text’), verbosity=‘low’)</li>
<li>top_logprobs: 0</li>
<li>truncation: disabled</li>
<li>usage: ResponseUsage(input_tokens=198, input_tokens_details=InputTokensDetails(cached_tokens=0), output_tokens=11, output_tokens_details=OutputTokensDetails(reasoning_tokens=0), total_tokens=209)</li>
<li>user: None</li>
<li>billing: {‘payer’: ‘openai’}</li>
<li>store: True</li>
</ul>
</details>
</div>
</div>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
    const viewSource = window.document.getElementById('quarto-view-source') ||
                       window.document.getElementById('quarto-code-tools-source');
    if (viewSource) {
      const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
      viewSource.addEventListener("click", function(e) {
        if (sourceUrl) {
          // rstudio viewer pane
          if (/\bcapabilities=\b/.test(window.location)) {
            window.open(sourceUrl);
          } else {
            window.location.href = sourceUrl;
          }
        } else {
          const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
          modal.show();
        }
        return false;
      });
    }
    function toggleCodeHandler(show) {
      return function(e) {
        const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
        for (let i=0; i<detailsSrc.length; i++) {
          const details = detailsSrc[i].parentElement;
          if (show) {
            details.open = true;
          } else {
            details.removeAttribute("open");
          }
        }
        const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
        const fromCls = show ? "hidden" : "unhidden";
        const toCls = show ? "unhidden" : "hidden";
        for (let i=0; i<cellCodeDivs.length; i++) {
          const codeDiv = cellCodeDivs[i];
          if (codeDiv.classList.contains(fromCls)) {
            codeDiv.classList.remove(fromCls);
            codeDiv.classList.add(toCls);
          } 
        }
        return false;
      }
    }
    const hideAllCode = window.document.getElementById("quarto-hide-all-code");
    if (hideAllCode) {
      hideAllCode.addEventListener("click", toggleCodeHandler(false));
    }
    const showAllCode = window.document.getElementById("quarto-show-all-code");
    if (showAllCode) {
      showAllCode.addEventListener("click", toggleCodeHandler(true));
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/AnswerDotAI\.github\.io\/cosette");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




<footer class="footer"><div class="nav-footer"><div class="nav-footer-center"><div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/AnswerDotAI/cosette/issues/new" class="toc-action"><i class="bi bi-github"></i>Report an issue</a></li></ul></div></div></div></footer></body></html>